### ISSUE TITLE
Compatibility Issue Between kduma-autoid/capacitor-sunmi-scanhead and kduma-autoid/capacitor-sunmi-uhf

### ISSUE THREAD

**Issue by brkos** [kduma-autoid/capacitor-sunmi-scanhead#33]
**Description:**
I am experiencing a compatibility issue when using the `kduma-autoid/capacitor-sunmi-scanhead` and `kduma-autoid/capacitor-sunmi-uhf` packages together in my project. During the release android app bundle build, I receive the following error message:

`Type com.sunmi.scanner.ICallBack$Default is defined multiple times:
C:\Users\user\.gradle\caches\8.9\transforms\02b71501499fa7a274a748e124479625\transformed\classes.jar:com/sunmi/scanner/ICallBack$Default.class,
C:\Users\user\.gradle\caches\8.9\transforms\04f762263adb062856ab65aea33b7e37\transformed\SunmiScannerSdk-release-v1.1.8-runtime.jar:com/sunmi/scanner/ICallBack$Default.class`

**Steps to Reproduce:**
Include both `kduma-autoid/capacitor-sunmi-scanhead` and `kduma-autoid/capacitor-sunmi-uhf` in your project dependencies.
Attempt to build the project in release .aab mode.
Observe the error message indicating the class conflict.

**Expected Behavior:**
Both packages should be compatible with each other without any class definition conflicts during the release build.

**Environment:**
Gradle version: 8.9
Android Studio version: Ladybug | 2024.2.1 Patch 2
Relevant Dependency Versions:
capacitor-sunmi-scanhead: 4.0.0
capacitor-sunmi-uhf: 4.0.0

**Additional Context:**
This issue seems to stem from both packages defining the same class (`com.sunmi.scanner.ICallBack$Default`), which leads to conflicts in the final build. The debug build is not affected; it fails during Task :app:mergeDexRelease. If I change the path of `capacitor-sunmi-scanhead/android/src/main/java` and the package ID to something like `com.sunmiX.*`, the build successfully passes.

**Comment by kduma** [comment]
Hello,

I can confirm that those two packages are indeed incompatible - due to that the Sunmi RFID SDK uses the same interface. 

I can try to prepare a compatible version of the scanhead plugin, but the functionality will be a bit reduced. Tell me what functions do you use from this package - and I will tell you if it will be affected.

**Comment by brkos** [comment]
Hello, thanks fo reply.
i use package with "bindOnLoad" option. And i go trought my code and find this API in use:

SunmiScanHead.scan(
SunmiScanHead.stop(
SunmiScanHead.getScannerModel(
SunmiScanHead.addListener('onScanResult', ..
SunmiScanHead.removeAllListeners(

Thanks

**Comment by kduma** [comment]
Hey,

I have created an ["lite" version of the plugin](https://github.com/kduma-autoid/capacitor-sunmi-scanhead-lite) which should be compatible with UHF plugin. 

Please try it and let me know if it works for you.
